### ISSUE TITLE
Can we keep this update with some latest version

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry-community/docker-registry-boshrelease#13]
Recently, docker release add some command for GC

https://github.com/docker/distribution/blob/master/docs/garbage-collection.md

Can we update the docker registry to some latest version?

Also can we add property to config.yml so that we can override its value in deployments
```
storage:
  delete:
    enabled: false
```

**Comment by jhunt** [comment]
I see no reason why not.  What version would you recommend?

**Comment by StanleyShen** [comment]
The latest one is 2.5.0, if there is no issue we should try to upgrade to it.
2.4.0 is enough for me.

**Comment by jriguera** [comment]
We are testing Registry 2.5.0 and we also have updated the packages and jobs with more properties (specially mirror and S3 storage settings). There are quite a few changes there but I am happy to submit a PR.

https://github.com/SpringerPE/docker-registry-boshrelease

**Comment by jhunt** [comment]
Please do!

**Comment by jhunt** [comment]
@jriguera I went ahead and merged your changed back into the project.  Is there a way you can make your blobs available, or at least give me the URLs you downloaded them from so I can go get them myself?

**Comment by jhunt** [comment]
Ah, found 'em.  Looks like it's working, @StanleyShen you may want to try a dev release from master.

I would like to figure out how to get #10 implemented, so that we can verify configuration via automated smoke tests.

**Comment by jhunt** [comment]
I just cut v3.2.0, which has dist 2.5.0 in it.

**Comment by jriguera** [comment]
Ups, sorry I haven't seen the notifications of this thread until now. Thanks for going ahead!
