### ISSUE TITLE
Docker Registry Notifications

### ISSUE THREAD

**Issue by jriguera** [cloudfoundry-community/docker-registry-boshrelease#18]
Hi,

We have implemented the [notifications feature of Docker Registry](https://docs.docker.com/registry/notifications/). It allows us to define a logstash endpoint to receive events in JSON format and save them in EL.

Repo: https://github.com/SpringerPE/docker-registry-boshrelease/tree/notifications

I think is better to accept first the PR which adds support for GCP and then submit a new PR with this feature. What do you think?

**Comment by jhunt** [comment]
I merged in your SpringerPE commits, o feel free to submit the PR for notifications.  Thanks!

**Comment by jriguera** [comment]
I have submitted a PR: https://github.com/cloudfoundry-community/docker-registry-boshrelease/pull/20
Closing this issue.

Thanks!
