### ISSUE TITLE
update releases with 3.2.2 

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry-community/docker-registry-boshrelease#23]
Not sure if this is something i can open a pr for, but 3.2.2 is out but /releases shows 3.2.1 as latest

**Comment by jhunt** [comment]
We had some pipeline issues that I think have since been fixed.  I'm cutting a 3.2.3 for the loopback bind fix in #24 so hopefully that makes it to the Github releases page.

**Comment by jhunt** [comment]
https://github.com/cloudfoundry-community/docker-registry-boshrelease/releases/tag/v3.2.3

3.2.3 is out and listed on Github!  \o/
