### ISSUE TITLE
push image to registry error

### ISSUE THREAD

**Issue by marcus-sds** [cloudfoundry-community/docker-registry-boshrelease#26]
When I try to push the image to registry, 
It's failing during upload. Would you check the errors?

* client log
docker/8dcbde80-30ae-4844-b5a7-e359a2cd7ac4:~# docker -D push docker-regi.xxxx.xxx/test:latest
The push refers to a repository [docker-regi.test.devground.io/test]
3d4d0124d9c1: Pushing [==================================================>] 27.19 MB
daae47e4368d: Pushing [==================================================>] 16.68 MB
b1764aeb4a1b: Pushing [===========================================>       ] 4.393 MB/5.029 MB
79239e7975dd: Pushing [========>                                          ] 6.809 MB/41.31 MB
a1c57052f585: Pushing [>                                                  ] 1.592 MB/470.6 MB
49907af65b0a: Pushing [==================================================>] 3.072 kB
4589f96366e6: Waiting
b97229212d30: Waiting
cd181336f142: Waiting
0f5ff0cf6a1c: Waiting
unauthorized: authentication required

* server log
./registry/registry.log:time="2017-11-01T08:09:33.889197638Z" level=error msg="response completed with error" environment=docker-registry-0 err.code="blob unknown" err.detail=sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913 err.message="blob unknown to registry" go.version=go1.7.3 http.request.host=docker-regi.test.devground.io http.request.id=aab9e83e-1764-43f4-8dc3-0f34d28ad83c http.request.method=HEAD http.request.remoteaddr=13.124.163.64 http.request.uri="/v2/test/blobs/sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913" http.request.useragent="docker/1.13.1 go/go1.7.5 git-commit/092cba3 kernel/4.4.0-87-generic os/linux arch/amd64 UpstreamClient(Docker-Client/1.13.1 \\(linux\\))" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.376849ms http.response.status=404 http.response.written=157 instance.id=5b100e29-37de-4429-8fee-7fbfdd057c4d service=registry vars.digest="sha256:ae79f251470513c2a0ec750117a81f2d58a50727901ca416efecf297b8a03913" vars.name=test version="v2.4.1+unknown"

**Comment by marcus-sds** [comment]
yes..I did check the .docker/config.json

**Comment by jhunt** [comment]
I have no idea.  Have you tried asking the upstream Docker project?  It might very well be a configuration issue with the deployment / this BOSH release, but I am unsure where to even start troubleshooting.

**Comment by marcus-sds** [comment]
We are testing registry with elb + gorouter + dockre regisry with ssl termination.
When we added below option at registry.conf http section, we could push the image.

http:
**"relativeurls: true"**

Thanks.

**Comment by jhunt** [comment]
We can.  Curious: what was the CLI invocation to push the Docker image CF App?

**Comment by jhunt** [comment]
See if 3.3.0 fixes this issue for you.  There is a new `docker.registry.relativeurls` spec

**Comment by marcus-sds** [comment]
I tried with 
"CF_DOCKER_PASSWORD=YOUR-PASSWORD cf push APP-NAME --docker-image REPOURL/IMAGE --docker-username USER"
It seems to be like below. Anyway it's working. Thanks.
relativeurls: <%= p('docker.registry.relativeurls') == true ? 'true' : 'false' %>

Is it possible to combine uaa to auth the registry?

**Comment by jhunt** [comment]
Glad the relativeurls thing worked out.

As for UAA, at this time the BOSH release does not support UAA.
