### ISSUE TITLE
Support Xenial Stemcell

### ISSUE THREAD

**Issue by jordanbcooper** [cloudfoundry-community/docker-registry-boshrelease#42]
This issue has a lot of extra work behind it. I've tested locally and have struggled with the latest ubuntu debian package for nfs-server. As with my other issue, I will continue testing and provide a PR, unless someone else has ideas. I've hit a wall so far with the latest nfs-server package not providing idmapd. I'm going to assume a number of the packages on this release are similarly unsupported on Xenial.

**Comment by jhunt** [comment]
I have quite a bit of experience with NFS on Xenial in BOSH.  Lemme see what I can do.

**Comment by jhunt** [comment]
@jordanbcooper if you could send me (DM in CF slack works) a manifest that has all the right configuration for NFS, that'd greatly speed things up.

**Comment by jhunt** [comment]
Managed to get a Trusty-based NFS deployment up and running in my lab.  Next steps:

- Re-tool my docker daemon to allow pushes to the insecure registry
- Push an image
- Verify the file made it to NFS
- Switch to Xenial
- Fix all the problems
- Validate the same way

After speaking with @jordanbcooper we decided that we are going to leave `debian_nfs_server` and `nfs_mounter` jobs as-is, and build new jobs (`nfs-server` and `nfs-client`) that can handle both Trusty and Xenial, and have better properties.  The legacy jobs will be retained for a few versions and then dropped.

**Comment by aad** [comment]
appreciate if you could get docker-registry working with Xenial, this is the last piece on trusty in our deployment :)

**Comment by jhunt** [comment]
@aad / @jordanbcooper can you take the `nfs-on-xenial` branch (https://github.com/cloudfoundry-community/docker-registry-boshrelease/tree/nfs-on-xenial) for a spin in a dev release deployment?

**Comment by aad** [comment]
@jhunt, i took a test and it looks good. thanks!

**Comment by jhunt** [comment]
I will ship a release this morning, once I get our CI/CD back online.

**Comment by jordanbcooper** [comment]
@jhunt I'm getting the following when trying to upgrade:

`registry-cache-worker/a1b40835-9189-4ed1-b39c-64cf49883f09: stdout | mount.nfs: mount(2): Permission deniedregistry-cache-worker/a1b40835-9189-4ed1-b39c-64cf49883f09: stdout | mount.nfs: access denied by server while mounting 192.168.53.150:/var/vcap/store
registry-cache-worker/a1b40835-9189-4ed1-b39c-64cf49883f09: stdout | mount.nfs: timeout set for Thu Jul 11 14:31:39 2019
registry-cache-worker/a1b40835-9189-4ed1-b39c-64cf49883f09: stdout | mount.nfs: trying text-based options 'timeo=10,intr,lookupcache=positive,vers=4,addr=192.168.53.150,clientaddr=192.168.53.152'
registry-cache-worker/a1b40835-9189-4ed1-b39c-64cf49883f09: stdout | Cannot mount NFS, exiting...`

**Comment by jordanbcooper** [comment]
I'm going to see if this is because I was already running an old version of docker-registry. I'll upgrade to 3.4.0, then upgrade to xenial?

**Comment by jordanbcooper** [comment]
Nope...same issue.

**Comment by jhunt** [comment]
What mounts are being exported by the NFS node?

**Comment by jordanbcooper** [comment]
If you mean the "share_path" property under nfs_server, it is /var/vcap/nfs

**Comment by jordanbcooper** [comment]
ahh...I may need to modify the manifest slightly for this new job. I'm not running the debian_nfs_server job.

**Comment by jhunt** [comment]
Is this now fixed in v3.5.2? https://github.com/cloudfoundry-community/docker-registry-boshrelease/releases/tag/v3.5.2

**Comment by jordanbcooper** [comment]
It appears I am able to upgrade a fresh docker registry (no data on nfs) with nfs, proxy, cache, and 2 workers without issue from 3.3.2 on Trusty to 3.5.2 on Xenial. If you want that tested before we call this "fixed" let me know, otherwise it looks good.

**Comment by jhunt** [comment]
Let's close it for now; if it reoccurs, we can reopen this issue, or file a new one.

🎉
