### ISSUE TITLE
Upload v2 release in s3 bucket

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry-community/docker-registry-boshrelease#8]
Hello.

Thanks for your work on this community release.

It looks like you should update the release hosted in your s3 bucket to version 2 and update the README.

This caused some confusion for me when I tried to upload the s3 hosted release and deploy with the current manifest templates.

Thanks!

**Comment by jhunt** [comment]
Your best bet for uploading final releases to your BOSH director is to you bosh.io (http://bosh.io/releases/github.com/cloudfoundry-community/docker-registry-boshrelease?all=1).

```
bosh upload release https://bosh.io/d/github.com/cloudfoundry-community/docker-registry-boshrelease
```
